add release action
akashic-games/actions pull request #1
Opened 2021-03-05 07:31 UTC by dera-

### 概要
akashic-games organizationのリポジトリで共通で使う予定のアクションとして、モノレポ以外のリポジトリをリリースする処理があるのでこちらの処理をアクション化しました(モノレポについてはリリース処理がnpm scriptsだけで完結するのでアクション化する必要は無いと判断しました)。

### やったこと
* モノレポ以外のリポジトリをリリースするアクション release の作成
* package.jsonやREADMEなどactionsリポジトリの土台を作成

2021-03-05 07:41 UTC, dera- commented
javascriptで書かれたアクションの場合利用しているパッケージを全てバンドルしたファイルをgit管理しておく必要があるため、release/dist/index.jsというビルド後のファイルを追加しました(ついでにバンドルするためのツールであるnccにも依存しています)。

2021-03-05 09:34 UTC, yu-ogi requested changes
1. 典型的な usage (利用例) の追記
2. 入力値のブラッシュアップ
   * 全リポジトリに影響があるので慎重に検討したい
   * アクションの入力値が `octokit.repos.createRelease()` のインタフェースに引っ張られすぎている印象がある

を対応いただきたいです。

2021-03-05 09:34 UTC, yu-ogi commented on package.json
> +  "name": "actions",
private ではありますが `@akashic/` は付けておいた方が良いかと。

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +#### 入力パラメータ
(must) usage がほしいです。

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +* `target_repository`: このアクションの対象リポジトリ。ただし、akashic-games organization に属するリポジトリ名を入力する必要がある。
[$GITHUB_REPOSITORY](https://docs.github.com/ja/actions/reference/environment-variables) や package.json の name から判断すべきなので無くしたいです。package.json と違う値が指定された場合も動作が不定ですし、オペミスとなりうる箇所はなるべく排除したいです。

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +* `target_branch`: このアクションの対象ブランチ。ここで入力したブランチの内容で Publish と GitHub での Tag 打ちが行われる。デフォルト値は master。
この値は利用側がリポジトリを checkout する段階で決めることで、この action に指定するものでは無いような気がします。

```yml
- uses: actions/checkout@v2
  with:
    ref: v2-master # この段階で定まる
- uses: akashic-games/actions/release@...
  with:
    ...
```

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +* `target_npm_tag`: publish したバージョンにここで入力した名前のタグが付けられる。デフォルト値はlatest。
package.json の publishConfig で指定するものとは異なるのでしょうか。

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +* `target_dir_path`: 対象リポジトリのルートパス。具体的には、package.json や CHANGELOG.md が配置されているパス。
[$GITHUB_WORKSPACE](https://docs.github.com/ja/actions/reference/environment-variables) ではだめなのでしょうか。個別に指定するメリットがいまいち見えてきません。

2021-03-05 09:34 UTC, yu-ogi commented on release/src/index.js
> +}).then(() => {
Node 12 って async/await 未サポートでしたっけ。async/await の方がわかりやすいかと思いました。

2021-03-05 09:34 UTC, yu-ogi commented on release/src/index.js
> +	tag: core.getInput("target_npm_tag"),
入力値は、コード内で個別に取得するのではなく先頭でまとめて定義しておきたいです。(将来的に関数に切り出すなど考えても)

```javascript

const input = {
  package: path.join(...),
  token: core.getInput(...),
  tag: core.getInput(...),
  ...
};

npmPublish({
  package: input.package,
  ...
})
...

```

2021-03-05 09:34 UTC, yu-ogi commented on release/src/index.js
> +const fs = require("fs");
この PullRequest で対応するかは別として、ビルド成果物をアップロードする方針ならばプロダクトコードは TypeScript で書きたいですね。

2021-03-05 09:34 UTC, yu-ogi commented on package.json
> +    "@zeit/ncc": "^0.22.3",
(質問) [公式文書](https://docs.github.com/ja/actions/creating-actions/creating-a-javascript-action#example-usage) では `@vercel/ncc` が利用されているようですが何か違いがあるのでしょうか。

2021-03-05 09:34 UTC, yu-ogi commented on package.json
> +    "build:release": "ncc build release/src/index.js -o release/dist",
アクションを追加するたびに `build:...` の npm-scripts を増やしていくという運用でしょうか。良い案が思い浮かぶわけでは無いですが保守コストが気になりますね。

2021-03-05 09:34 UTC, yu-ogi commented on package.json
> +    "test:generate-release-note": "node ./release/src/__test__/generateReleaseNote.test.js"
この PullRequest での対応はお任せですが、テストフレームワークの導入は早急に行いたいです。

2021-03-05 09:34 UTC, yu-ogi commented on README.md
> +npm test
このリポジトリ自体をテストする workflow も欲しいですね。

2021-03-05 09:34 UTC, yu-ogi commented on release/src/__test__/generateReleaseNote.test.js
> +const assert = require('assert');
linter も早急に導入したいですね。(シングルクォーテーションになっている)

2021-03-05 13:19 UTC, dera- commented
ありがとうございます。各コメントには返答しますが、即対応予定のものと別PRで行いたいものを以下に書いてみました。

### 即対応予定
* アクションの入力パラメータの修正。ちなみに、現状のものについては↓のように考えています
  * target_repository: package.jsonのnameで分かるので多分要らない
  * target_branch: git release note作る時に必要らしいが詳細は分かってないので調べてみます
  * target_npm_tag: package.jsonの方で解決できるので要らない
  * target_dir_path: $GITHUB_WORKSPACEでいけるかもなので調べてみます
  * git_hub_token: 要る
  * npm_token: 要る
* usage
  * usageは例えば https://github.com/actions/checkout のREADMEに書いてあるような感じで大丈夫でしょうか？
* テストするワークフロー追加
  * npm testを実行するだけだなのでこれは今から作っても良さそう

### 後回しにしたいもの
* typescript, testフレームワーク, linter, buildの方法見直し
  * 保守性も考えてsrcはtypescriptにしておきたいですが、そうするとtestフレームワーク, linter, buildの方法も同時に修正が必要になると思うので、これらは同じタイミングやりたいと思ってます。また、ボリューム的にも大きめの修正になるのでは別対応にさせていただきたいかなと思ってます。

2021-03-05 13:20 UTC, dera- commented on package.json
> +  "name": "actions",
あ、、確かにそうですね。こちら修正しておきます

2021-03-05 13:22 UTC, dera- commented on README.md
> +#### 入力パラメータ
了解しました、こちら追加しておきます

2021-03-05 13:25 UTC, dera- commented on README.md
> +* `target_repository`: このアクションの対象リポジトリ。ただし、akashic-games organization に属するリポジトリ名を入力する必要がある。
actionであればGITHUB_REPOSITORYから取得できそうな気がしますね。できなかったとしてもpackage.jsonもありますし、これは消せそうな気がします。仰る通りオペミスのもとになり得るので、これに限らずできるだけ削れる入力パラメータは削っていきたいですね。。

2021-03-05 13:28 UTC, dera- commented on README.md
> +* `target_branch`: このアクションの対象ブランチ。ここで入力したブランチの内容で Publish と GitHub での Tag 打ちが行われる。デフォルト値は master。
仰る通りbranchはcheckout時に指定すればそれ以降は使わない値でここで指定するも本来無いのですが、Release Note作成時に必要になってしまうパラメータなので用意してしまったところです。こちら削れないかの検討をしてみます

2021-03-05 13:29 UTC, dera- commented on README.md
> +* `target_npm_tag`: publish したバージョンにここで入力した名前のタグが付けられる。デフォルト値はlatest。
あー、publishConfig で指定すればここでの指定は不要ですね。こちらも削っておきます

2021-03-05 13:30 UTC, dera- commented on README.md
> +* `target_dir_path`: 対象リポジトリのルートパス。具体的には、package.json や CHANGELOG.md が配置されているパス。
外部からの入力以外でパスを知る手段は無いと思っていましたが、GITHUB_WORKSPACEでできそうな気はしますね。こちらも削れないか検討します

2021-03-05 13:33 UTC, dera- commented on release/src/index.js
> +}).then(() => {
top-level awaitはnode14からのサポートみたいですね。https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.3.0

一応、async/await 試してはみましたがやはりエラーが出てだめでしたね。。
ただ、typescriptに変えればasync/await使えそうなので、その時に修正しようかなと思います。

2021-03-05 13:34 UTC, dera- commented on release/src/index.js
> +	tag: core.getInput("target_npm_tag"),
なるほど、こちらそのように対応してみます。

2021-03-05 13:35 UTC, dera- commented on release/src/index.js
> +const fs = require("fs");
仰る通りですが、一旦今回での対応は見送って別PRでの対応とさせていただきたいです

2021-03-05 13:36 UTC, dera- commented on README.md
> +npm test
了解しました、こちらは対応します。

2021-03-05 13:38 UTC, dera- commented on package.json
> +    "@zeit/ncc": "^0.22.3",
お、、、別スコープのnccがあるんですね。。？
別資料を見てたので、`@zeit/ncc`を入れてしまいましたが`@vercel/ncc`でも問題ないはず。公式文書で書かれている方を使った方が良さそうですね

2021-03-05 13:40 UTC, dera- commented on package.json
> +    "build:release": "ncc build release/src/index.js -o release/dist",
その方針で考えていました > アクションを追加するたびに build:... の npm-scripts を増やしていくという運用
しかし仰る通り、保守コスト的にあまりよろしくはないビルド方法かと思いますので、ソースコードをtypescriptに書き直す時に同時にビルド方針を見直そうかと思っています

2021-03-05 13:42 UTC, dera- commented on package.json
> +    "test:generate-release-note": "node ./release/src/__test__/generateReleaseNote.test.js"
テストフレームワークも今入れてもtypescript導入時に修正が必要になると思うので、typescript導入時に同時に導入したい気持ちでいます。

2021-03-05 13:44 UTC, dera- commented on release/src/__test__/generateReleaseNote.test.js
> +const assert = require('assert');
こちらもtypescriptやテストフレームワーク導入時に対応ですかね。おそらくこのテストコード自体その時に消えるのではないかと思います。
でも、このシングルクォーテーション自体は修正しておきます

2021-03-08 01:43 UTC, yu-ogi commented on release/src/index.js
> +}).then(() => {
async の即時関数を間に挟んでもダメでしょうか。

```javascript
(async () => {
  await ...;
})();
```

2021-03-08 06:12 UTC, dera- commented on release/src/index.js
> +}).then(() => {
なるほど、こちら試してみます

2021-03-10 00:04 UTC, yu-ogi commented on README.md
> +### Usage (利用例)
他の見出しが日本語なので単に「利用例」で良いかと。

2021-03-10 00:04 UTC, yu-ogi commented on README.md
> +```
すこし見にくいので yml でハイライトしたいです。

2021-03-10 00:04 UTC, yu-ogi commented on release/src/index.js
> +		const repositoryInfo = process.env.GITHUB_REPOSITORY.split("/");
`process.env` の値も `targetDirPath` と同様に先頭で定義しておきたいです。

2021-03-10 00:04 UTC, yu-ogi commented on release/src/index.js
> +			access: "public"
よくわかっていないのですが package.json の publishConfig.access の値を無視してしまっても問題ないのでしょうか。(それとも package.json の publishConfig の値が優先される?)

2021-03-10 00:04 UTC, yu-ogi commented on README.md
> +# relaseアクション利用前にactions/checkout等で対象のgithubリポジトリをcheckoutしておく必要があります
* 下のサンプルを見れば自明なのでこのコメントは不要かと。
* `relase` -> `release`

2021-03-10 00:04 UTC, yu-ogi commented on release/action.yml
> +name: release @akashic package
`@akashic` に限らなくても良いのでは。

2021-03-10 00:04 UTC, yu-ogi commented on README.md
> +以下のコマンドを実行
ビルドすることで

1. どのようなファイル (ncc でビルドされた js ファイル) が
2. どこのディレクトリに

生成されるかは最低限記載しておきたいです。

2021-03-10 06:46 UTC, dera- commented on README.md
> +### Usage (利用例)
了解しました、そのように修正しました

2021-03-10 06:47 UTC, dera- commented on README.md
> +```
了解しました、こちらymlを付けておきました

2021-03-10 06:48 UTC, dera- commented on release/src/index.js
> +		const repositoryInfo = process.env.GITHUB_REPOSITORY.split("/");
了解しました、環境変数の値が元になっているものに関しては先頭で定義するように修正しました

2021-03-10 06:52 UTC, dera- commented on release/src/index.js
> +			access: "public"
このnpmPublish関数でやっていることは結局は`npm publish`コマンドを実行しているだけなので publishConfigの設定の方が優先されるはずです。https://github.com/JS-DevTools/npm-publish/blob/master/src/npm.ts#L79
ですが、デフォルトの動作が`npm publish`の動作と変わる(npm publish の accessオプションのデフォルト値はrestricted)のは若干の気持ち悪さがあるので、このaccessオプションの指定は削除しておきます。

2021-03-10 06:52 UTC, dera- commented on README.md
> +# relaseアクション利用前にactions/checkout等で対象のgithubリポジトリをcheckoutしておく必要があります
了解しました、こちらのコメントは削除しておきました

2021-03-10 06:53 UTC, dera- commented on release/action.yml
> +name: release @akashic package
確かにそうですね。@akashicでなくても利用できるアクションではあるので`release package`としておきます

2021-03-10 06:55 UTC, dera- commented on README.md
> +以下のコマンドを実行
了解しました、ビルド成果物が生成されることについて追記しておきました。あと、一応開発者向けにそれらの生成物はgit管理が必要な旨も記載しておきました。

2021-03-10 06:58 UTC, dera- commented on README.md
> +* スコープ化された公開パッケージの場合、package.jsonの`publishConfig.access`にtrueを指定する必要があります。
実質的にreleaseアクションというより`npm publish`コマンド自体への注意点になってしまっているので、不要かもしれないですが、このアクションを前提知識なしで利用した時に起こりうる問題かなぁと老婆心で追記してみました。不要であれば削除します

2021-03-10 07:19 UTC, yu-ogi commented on README.md
> +* スコープ化された公開パッケージの場合、package.jsonの`publishConfig.access`にtrueを指定する必要があります。
https://docs.npmjs.com/cli/v7/using-npm/config#access

「`"public"` を指定する必要がある」かと。

2021-03-10 07:19 UTC, yu-ogi commented on release/src/index.js
> +			name: "Release " + version,
過去のリリースノートを見る限りここは `"Release v" + version` ではないでしょうか。

2021-03-10 07:19 UTC, yu-ogi commented on package.json
> +  "license": "UNLICENSED",
このあたり (author, license) 無指定で大丈夫ですか?

2021-03-10 08:43 UTC, dera- commented on README.md
> +* スコープ化された公開パッケージの場合、package.jsonの`publishConfig.access`にtrueを指定する必要があります。
あ、、、すみません。表記完全に誤ってました。。修正しておきます

2021-03-10 08:44 UTC, dera- commented on release/src/index.js
> +			name: "Release " + version,
あ、、そうでした。そのように修正しておきます。

2021-03-10 08:46 UTC, dera- commented on package.json
> +  "license": "UNLICENSED",
privateですが、その辺りの表記は必要でしたね。。こちら修正しておきます。

2021-03-10 23:41 UTC, yu-ogi approved these changes
LGTM です。

2021-03-10 23:41 UTC, yu-ogi commented on release/src/__test__/generateReleaseNote.test.js
> +	const changelog = `
(imo) これと `changelog2` ですが try 節の外で定義しておきたいですね。インデントが無視されてしまっているので。

2021-03-10 23:41 UTC, yu-ogi commented on package.json
> +  "license": "MIT",
(imo) LISENCE ファイルを追加したほうが良いかもです。

2021-03-11 05:34 UTC, dera- commented on release/src/__test__/generateReleaseNote.test.js
> +	const changelog = `
了解しました、こちら修正しておきます

2021-03-11 05:35 UTC, dera- commented on package.json
> +  "license": "MIT",
あ、、こちらも完全に失念していました。。READMEへの記載とともにファイル追加しておきます

2021-03-17 07:18 UTC, yu-ogi commented on package.json
> +    "build:release": "ncc build release/src/index.js -o release/dist",
https://docs.npmjs.com/cli/v7/using-npm/workspaces

npm v7 で利用可能な workspace を利用してアクションごとにサブリポジトリを作るというのも一案かもしれません。
lerna ほど高機能なモノレポマネージは不要そうですし、ルートで全てのアクションをビルドするというのも非効率な気がするので。

2021-03-17 08:00 UTC, dera- commented on package.json
> +    "build:release": "ncc build release/src/index.js -o release/dist",
ありがとうございます。
確かにlernaよりは手軽にディレクトリ毎にビルドやテストする仕組みは欲しいと思っていた感じです。
ちょっとこちら検討してみようと思います

2021-03-18 08:23 UTC, yu-ogi requested changes

2021-03-18 08:23 UTC, yu-ogi commented on README.md
> +  uses: akashic-games/actions/release@master
すいません、一点考慮漏れがありました。
こちらは他と慣習を合わせるという意味でも `v~` というタグを付けるという運用が望ましいように思います。
なのでこちらは以下のように指定できるようにしておきたいです。

```suggestion
  uses: akashic-games/actions/release@v1
```
```

2021-03-18 09:07 UTC, dera- commented on README.md
> +  uses: akashic-games/actions/release@master
ありがとうございます。中にはmasterブランチを指定させるアクションもあるのでこのままでも問題ないかと思いましたが、確かに`v~`で指定するものが多数のようですので、こちらのコミットを取り込まさせていただきます。
今後は`v~`のタグを作って、破壊的変更があればバージョンアップしたタグを作る方針にしていこうかと思っています

2021-03-18 09:26 UTC, yu-ogi approved these changes

2021-04-01 04:55 UTC, xnv approved these changes

2021-04-01 08:53 UTC, merged