actionsリポジトリのリファクタリング
akashic-games/actions pull request #2
Opened 2021-03-29 09:09 UTC by dera-

### やったこと
* アクションのソースコードとテストコードをtypescriptで書く
* testフレームワーク(jest)の導入
* linter(eslint)とformatter(prettier)の導入
* 各アクション毎にビルド・テストを可能にするためにnpm v7 から導入された[workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)を利用

2021-03-29 09:24 UTC, dera- commented on .github/workflows/test.yml
> +  NODE_VERSION: 15
npm v7のworkspacesを利用するためにnodeのバージョンを上げました。ただ、このバージョンはLTSではないので利用していいのか若干半信半疑ですが。。

2021-03-29 09:24 UTC, dera- commented on package.json
> +    "test:release": "cd release && npm test && cd .."
悩み所1：[workspacesのマニュアル](https://docs.npmjs.com/cli/v7/using-npm/workspaces)を見たところ`--workspaces`オプションでworkspacesに指定した全リポジトリのnpm scriptsを実行できるみたいなのですが、実際はできなかったのでそれができずこのように各リポジトリのテストを1つ1つ定義する必要がある形になってしまいました。。この辺りについて何かご存知であれば教えていただきたいです

2021-03-29 09:24 UTC, dera- commented on package.json
> +  ],
悩み所2：この書き方だとアクションを追加する度に毎回ここに追記が必要になるので、`packages/*`といった感じに定義しておいてpackages下にアクションを置くようにしておけばその必要はなくなりますが、破壊的変更になってしまう且つaction指定時の名前が若干長めになってしまうので変えてしまってよいものか悩んでいます。

2021-03-30 01:52 UTC, yu-ogi requested changes
* 特定の環境 (node, npm のバージョン) でないと正常に動作しないため package.json の engines の指定が必須になるかと思います。
   * c.f. https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
* 同様のことを README に記載しておきたいです。

2021-03-30 01:52 UTC, yu-ogi commented on package.json
> +  ],
流石にこの追記は許容してよいかと思います。

2021-03-30 01:52 UTC, yu-ogi commented on release/.eslintrc
> +{
(imo) ファイルが増えてしまうので package.json に記述してしまっても良いかなと思いました。
c.f. https://eslint.org/docs/2.0.0/user-guide/configuring

2021-03-30 01:52 UTC, yu-ogi commented on release/src/__tests__/generateReleaseNoteSpec.ts
> +	const changelog = `
インデントがずれてしまうので `describe` より前で定義しておきたいです。

2021-03-30 01:52 UTC, yu-ogi commented on package.json
> +    "test:release": "cd release && npm test && cd .."
以下の環境では正常に実行 (`npm test --workspaces`) できるようでした。
- macOS Catalina 10.15.7
- node 15.11.0
- npm 7.6.0

2021-03-30 01:52 UTC, yu-ogi commented on release/prettier.config.json
> +{
(imo) ファイルが増えてしまうので package.json に記述してしまっても良いかなと思いました。
c.f. https://prettier.io/docs/en/configuration.html

2021-03-30 01:52 UTC, yu-ogi commented on release/jest.config.js
> +module.exports = {
(imo) ファイルが増えてしまうので package.json に記述してしまっても良いかなと思いました。
c.f. https://jestjs.io/ja/docs/configuration

2021-03-30 01:52 UTC, yu-ogi commented on release/package.json
> +  "description": "action to relase akashic oss",
relase になっています。

2021-03-30 14:14 UTC, dera- commented on package.json
> +  ],
了解しました、アクションはここに追加していく運用にしようかと思います。

2021-03-30 14:37 UTC, dera- commented on release/.eslintrc
> +{
了解です。ここに記載している内容をpackage.jsonに移します

2021-03-30 14:37 UTC, dera- commented on release/src/__tests__/generateReleaseNoteSpec.ts
> +	const changelog = `
了解しました、そのように修正します。

2021-03-30 14:39 UTC, dera- commented on release/prettier.config.json
> +{
こちらもpackage.jsonに移しておきます

2021-03-30 14:39 UTC, dera- commented on release/jest.config.js
> +module.exports = {
ありがとうございます、こちらもpackage.jsonに移しておきます

2021-03-30 14:40 UTC, dera- commented on release/package.json
> +  "description": "action to relase akashic oss",
あ。。すみません、ありがとうございます。こちら修正します

2021-03-30 14:42 UTC, dera- commented on package.json
> +    "test:release": "cd release && npm test && cd .."
お、そうなんですね。ちなみに僕の環境は以下の通りでした。
* Ubuntu 14.04.6 LTS
* node 15.12.0
* npm 7.6.3

Windowsでも試してみますかね？

2021-03-31 04:30 UTC, yu-ogi commented on README.md
> +npm run build --workspaces
うーん、このコマンドは上述の環境ではうまく行かないですね。
対応状況によっては lerna の利用を検討しても良さそうですね。

2021-03-31 04:30 UTC, yu-ogi commented on release/package.json
> +    "bundle": "ncc build lib/index.js -o dist -m",
こちら一旦 js ファイルに変換しているみたいですが、 ts ファイルから直接変換することはできないのでしょうか。
[公式の README](https://github.com/vercel/ncc#with-typescript) を見るとできそうに見えましたが。

2021-03-31 04:30 UTC, yu-ogi commented on release/package.json
> +      "<rootDir>/src/__tests__/*Spec.ts"
[公式の文書](https://jestjs.io/ja/docs/configuration#testmatch-arraystring) を見るに `.spec.ts` の方が推奨されているように思います。

2021-03-31 07:13 UTC, dera- commented on release/package.json
> +    "bundle": "ncc build lib/index.js -o dist -m",
なるほど、tsファイルから直接バンドルできないか試してみようと思います

2021-03-31 07:23 UTC, dera- commented on release/package.json
> +      "<rootDir>/src/__tests__/*Spec.ts"
デフォルトだと`.spec.ts`や`.test.ts`を見に行くんですね。了解しました、であればテストファイルを`.spec.ts`にリネームしておこうと思います

2021-03-31 07:45 UTC, dera- commented on README.md
> +npm run build --workspaces
うーん、、やはりLTSではないバージョンにしか対応していないのが関係しているんですかね？
workspaceがどの環境でも安定して使えるようになるまでlernaを使って後から移行するという対応が現実的なのではという気がしていますね

2021-03-31 07:46 UTC, yu-ogi commented on package.json
> +    "test:release": "cd release && npm test && cd .."
すいません、上記コメントは誤りでこちらでも同様に動作しませんでした。 (`test:release` の内容が単に実行されているだけでした)
調査のため [ミニマムの workspaces を作成してみました](https://github.com/yu-ogi/workspaces-test) が、これを試す限りどうやら Node 14 系 (`14.16.0`) だと正常に `--workspaces` が働くみたいでした。
このリポジトリに対しては `No workspaces found!` と出てしまうみたいでそれについては精査できていませんが、 Node のバージョンで `--workspaces` の挙動が変化する可能性があるみたいです。

2021-03-31 08:08 UTC, yu-ogi commented on package.json
> +    "test:release": "cd release && npm test && cd .."
どうやら npm-scripts を次のようにベタ書きしたら `npm run build --workspaces` および `npm test --workspaces` が正常に動作するみたいでした。原因が不明ですが、観測的には workspaces 内で `npm run ...` を入れ子的に実行してしまうと問題が発生してしまうみたいです。

```js
  "scripts": {
    "prepare": "npm run build",
    "build": "tsc && ncc build lib/index.js -o dist -m && prettier --write \"src/**/*.ts\"",
    "test": "jest && eslint \"src/**/*.ts\" --fix"
  },
```

環境は以下の通りです。
* macOS Catalina 10.15.7
* node 14.16.0
* npm 7.7.6

2021-03-31 08:17 UTC, yu-ogi commented on package.json
> +    "test:release": "cd release && npm test && cd .."
以上のことを鑑みるに、モノレポの管理は lerna の方が現時点では安全かなと思いました。
(lerna.json を追加する程度なので npm workspace ⇔ lerna の追従コストもそこまで大きくないはずですし)

2021-03-31 08:29 UTC, dera- commented on package.json
> +    "test:release": "cd release && npm test && cd .."
調査ありがとうございます！そもそもnpm7にデフォルトで対応しているのはnode15からなのに、node14で且つnpm7の環境にする必要があるというのは厳しい感じありますからね。。
了解しました、lerna入れてみようと思います。

2021-04-01 01:55 UTC, yu-ogi commented on lerna.json
> +      ]
hoist を有効にしたいです。

2021-04-01 01:55 UTC, yu-ogi commented on release/package.json
> +    "prepare": "npm run build",
root で npm i しただけでビルドが実行されるようになっていますが、今後アクションの数が増えたときに毎回全てのパッケージをビルドするのは時間的にも無駄に思えます。
ビルドコマンドは npm i のタイミングとは切り離したほうが無難かと思いますがいかがでしょう。

2021-04-01 01:55 UTC, yu-ogi commented on lerna.json
> +        "--no-package-lock"
`--no-package-lock` を指定していますが `release/package-lock.json` はいつのタイミングで生成されるものなのでしょう?

2021-04-01 01:55 UTC, yu-ogi commented on release/tsconfig.json
> +    "declaration": true,
js ファイルを生成しない以上 `outDir` や `declaration` の指定は意味をなさなそうに見えます。

2021-04-01 01:55 UTC, yu-ogi commented on release/package.json
> +  "name": "@akashic/actions-release",
(imo) lerna を利用するなら `release` という名前にしてしまっても良さそうですね。コマンドラインでの `--scope` の指定を簡潔にするためです。
```sh
npx lerna --scope=release build # release のみ個別にビルド
```

2021-04-01 06:21 UTC, dera- commented on lerna.json
> +      ]
了解しました、こちら有効にしておきます

2021-04-01 06:23 UTC, dera- commented on release/package.json
> +    "prepare": "npm run build",
確かに仰る通りですね。さらに言うと、このパッケージはpublishするわけではないのでprepareを宣言しておく意味はなさそうなので、削除しておこうと思います

2021-04-01 06:30 UTC, dera- commented on release/package.json
> +  "name": "@akashic/actions-release",
lernaでそういった指定ができるんですね。であればそのように修正してみようかと思います(actionsを接頭辞に着ける理由も特にありませんし)。

2021-04-01 06:31 UTC, dera- commented on release/tsconfig.json
> +    "declaration": true,
了解しました、こちら削除しておきます

2021-04-01 06:47 UTC, dera- commented on lerna.json
> +        "--no-package-lock"
あー、、releaseディレクトリ内でnpm installした時に生成されますがそれはlernaの正しい使い方ではないはずで、正しい使い方をすればpackage-lock.jsonは生成されないのでこのオプションは削除しても良さそうな気がしますね

2021-04-01 08:51 UTC, yu-ogi commented on lerna.json
> +        "--no-package-lock"
> 正しい使い方をすればpackage-lock.jsonは生成されない

[lerna bootstrap で各リポジトリで npm install が実行される](https://github.com/lerna/lerna/tree/main/commands/bootstrap#usage) ので通常であれば「package-lock.json が生成される」では..?
正しい使い方というのがよくわかっていないです。

2021-04-01 09:03 UTC, yu-ogi commented on lerna.json
> +        "--no-package-lock"
[CI 環境では npm ci が実行される](https://github.com/lerna/lerna/tree/main/commands/bootstrap#--no-ci) ようなのでテストが落ちているみたいですね。

2021-04-01 09:08 UTC, dera- commented on lerna.json
> +        "--no-package-lock"
あ、すみません。。勘違いでした。lerna bootstrapでrelease下にもpackage-lock.jsonが生成されますね。今の所lerna bootstrap実行時に`--no-package-lock`を付ける理由はなさそうなので一旦このオプションは無しにします

2021-04-01 09:09 UTC, dera- commented on lerna.json
> +        "--no-package-lock"
なるほど、、では`--no-ci`オプションを付けてみますか

2021-04-01 09:09 UTC, yu-ogi commented on lerna.json
> +        "--no-package-lock"
なので `--no-package-lock` を削除しつつ package-lock.json は手元で生成するのが正しい使い方な気がしています。

2021-04-01 09:33 UTC, yu-ogi commented on package.json
> +    "postinstall": "lerna bootstrap --no-ci",
各リポジトリに package-lock.json が存在すれば `--no-ci` フラグは不要では?
CI で npm ci を実行しない積極的な理由って何でしょうか。

2021-04-01 09:33 UTC, yu-ogi commented on release/src/index.ts
>  const npmPublish = require("@jsdevtools/npm-publish");
`import npmPublish = require(...)` とは書けないのでしょうか。`@typescript-eslint/no-var-requires` の指定も不要になりそうです。

2021-04-01 09:33 UTC, yu-ogi commented on release/README.md
> +npm install
prepare が無くなったので `npm run build` が正しいかと思います。

2021-04-01 09:33 UTC, yu-ogi commented on release/.gitignore
> +!dist/index.js
あー、tsconfig の declaration を省略すると dist に型定義が出力されるみたいですね。
前言撤回で恐縮ですが `declaration: false` に指定すればこちらは指定せずに済みそうです。

2021-04-02 07:59 UTC, dera- commented on release/.gitignore
> +!dist/index.js
了解しました。tsconfigの方に`declaration: false`を指定してこの.gitignoreは削除しておきます

2021-04-02 08:00 UTC, dera- commented on release/README.md
> +npm install
仰る通りですね、こちらも修正しておきます

2021-04-02 08:08 UTC, dera- commented on release/src/index.ts
>  const npmPublish = require("@jsdevtools/npm-publish");
すみません、npm-publishは型定義ファイルが無いものかと思ってこのような書き方をしていたのですが、存在していましたのでそれを参照するように修正しました。
ただ、このファイルの別箇所でpackage.jsonを読み込む処理があって、そこではrequireがどうしても必要になるのでそこは`eslint-disable-next-line`コメントを使用しつつrequireを利用しようと思います

2021-04-02 08:11 UTC, dera- commented on package.json
> +    "postinstall": "lerna bootstrap --no-ci",
すみません、ここも勘違いでした。`--no-ci`オプションが無いとCIでのテストが落ちるものかと思っていましたが、仰る通り`package-lock.json`があれば不要でした。ですので、このオプションは削除しておきます

2021-04-02 09:24 UTC, yu-ogi approved these changes
全体的に LGTM ですが、 `v1.~~` の github tag を何時どのタイミングで誰が打つのかは別途検討する必要がありそうです。

2021-04-02 09:24 UTC, yu-ogi commented on README.md
> -npm run build
https://github.com/akashic-games/actions/pull/2#discussion_r605508741

2021-04-02 09:24 UTC, yu-ogi commented on release/package.json
> +    "bundle": "ncc build src/index.ts -o dist -m",
紛らわしいので build に統一してよいかと。

2021-04-02 09:24 UTC, yu-ogi commented on release/package.json
> +    "lint": "eslint \"src/**/*.ts\" --fix"
(imo) `test:lint` として npm-run-all で `npm run test:*` と呼び出した方がわかりやすいかなと思いました。

2021-04-02 09:24 UTC, yu-ogi commented on README.md
> -アクションを更新するためにはビルド生成物をgit管理する必要があります。
(imo) せっかくなのでアクションを個別にビルドするコマンド例も追記しておいても良さそうに思いました。

```bash
npx lerna run build --scope=release # release のみをビルド
```

2021-04-02 09:24 UTC, yu-ogi commented on README.md
> +以下のコマンドを実行。
「すべてのリポジトリに対してビルドが実行される」という旨は記載しておきたいです。

2021-04-05 05:31 UTC, dera- commented on README.md
> -npm run build
あ、こちらも同様に修正する必要がありましたね。。ありがとうございます。

2021-04-05 05:37 UTC, dera- commented on release/package.json
> +    "bundle": "ncc build src/index.ts -o dist -m",
bundleのスクリプトをbuildにそのまま移すということですよね。それだとtsファイルのトランスパイルのみしたい場合に実行するスクリプトがなくなってしまうので、これ自体は残しておきたいんですよね。`"bundle"`という名前が紛らわしいということであれば`"build:ts"`とかにリネームするのはどうでしょうか？

2021-04-05 05:38 UTC, dera- commented on release/package.json
> +    "lint": "eslint \"src/**/*.ts\" --fix"
なるほど、そちら検討してみます

2021-04-05 05:46 UTC, dera- commented on README.md
> -アクションを更新するためにはビルド生成物をgit管理する必要があります。
了解しました、こちらtips的情報として記載しておこうと思います。

2021-04-05 05:47 UTC, dera- commented on README.md
> +以下のコマンドを実行。
了解しました、その旨を追記しておきます

2021-04-05 06:40 UTC, yu-ogi commented on release/package.json
> +    "bundle": "ncc build src/index.ts -o dist -m",
> それだとtsファイルのトランスパイルのみしたい場合

その使い分けを利用側で区別しなければならないのが不便かなと思ったのですが、formatter を (一時的にも) 通したくないケースがあるというということですかね。それであれば現状のままでも良い気がします。

2021-04-05 07:16 UTC, dera- commented on release/package.json
> +    "bundle": "ncc build src/index.ts -o dist -m",
具体的ケースは思いついていないのですが、選択肢として残しておくのは有りかと思っています。
了解しました、ではこの名前のままにしておこうと思います

2021-04-05 08:20 UTC, yu-ogi commented
> 全体的に LGTM ですが、 v1.~~ の github tag を何時どのタイミングで誰が打つのかは別途検討する必要がありそうです。

📝  一案: master ブランチに merge されたタイミングで `v(cat package.json | jq -r .version)` の tag を git push する workflow を追加する

2022-06-14 05:40 UTC, closed without merging